name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup tools
      run: sudo apt install -y libsdl2-dev

    - name: Cleanup object files
      run: rm -rf obj

    - name: Create obj directory
      run: mkdir obj
        
    - name: Build files
      run: make
      
    - name: Testing
      run: |
        chmod +x test.sh
        ./test.sh
